package laska.daily.bible.meditation.domain.analytics

enum class CounterType {

    SESSION_COUNT,
    DAILY_REFLECTION_AUDIO_PLAY,
    DAILY_REFLECTION_AUDIO_COMPLETED,
    DAILY_REFLECTION_TEXT,
    SUPPORT_COUNT,
    DONATE_MAIN_SCREEN,
    DONATE_MENU,
    DONATE_ERIP,
    DONATE_BELARUS_NOT,
    DONATE_CLOSE,
    DONATE_CONFIRMED,
    DONATE_UNCONFIRMED,
    FROM_RUSSIA,
    FROM_EU,
    FROM_OTHER,
    POP_UP_SHOWN,
    POP_UP_LATER_CLICKED,
    POP_UP_DISMISSED,
    POP_UP_ERIP_CLICKED,
}